### PR TITLE
Refactoring libsec

### PR DESCRIPTION
**Pull request by riyazhakki**
#### Describe Bug or Feature

Extending libsec to include more security related API.

#### Describe Your Change

These new API would help to set security context at the server and using it while running the job.

#### Attach Test and Valgrind Logs/Output

ID | TOTAL | FAIL | ERROR | TIMED OUT | SKIP | PASS
-- | -- | -- | -- | -- | -- | --
8215 | 4127 | 4 | 1 | 0 | 1 | 4121

### CODE REVIEW

**Comment by bhroam** [comment]
@riyazhakki Could you please fill out the description of the PR more?  What is the purpose of this refactor?

**Comment by riyazhakki** [comment]
> @riyazhakki Could you please fill out the description of the PR more? What is the purpose of this refactor?

Hi @bhroam, 
I have updated the description of the PR.

**Comment by bhroam** [comment]
@riyazhakki Thanks!

**Comment by riyazhakki** [comment]
Raising this PR on different branch.

**Pull request closed without merging**
