### PR TITLE
Node state change logging and test improvements

### PR DESCRIPTION
**Pull request by monkeystate**
This pull request contains several improvements to the functional test for the modifyvnode event, as well as removal of an unused and incorrectly functioning vnode constant. The purpose of these changes is to improve the accuracy and robustness of node state change logging. This pull request is aimed at resolving the following issues:

https://github.com/openpbs/openpbs/issues/2216
https://github.com/openpbs/openpbs/issues/2241
https://github.com/openpbs/openpbs/issues/2249

### CODE REVIEW

**Comment by bayucan** [comment]
@monkeystate : code looks good. Can you attach the ptl test log for evidence of testing? Thanks.

**Comment by monkeystate** [comment]
Here is a smoke test run:
[ptl-smoke20210204.txt](https://github.com/openpbs/openpbs/files/5953868/ptl-smoke20210204.txt)

Here is a test run on a 2-mom deployment of all node state change tests in pbs_hook_modifyvnode_state_changes.py:
[ptl-pbs_hook_modifyvnode_state_changes20210204.txt](https://github.com/openpbs/openpbs/files/5953852/ptl-pbs_hook_modifyvnode_state_changes20210204.txt)

**Comment by monkeystate** [comment]
Hello @bayucan,

Please find the ptl logs attached, per your request. Also for the sake of documentation/completeness I filed a third issue that is fixed as part of this pull request (https://github.com/openpbs/openpbs/issues/2249).

Thank you

**Review by bayucan — APPROVED** [review]
Looks good.

**Comment by bayucan** [comment]
@openpbs/openpbs-maintainers : this needs a second reviewer before we can merge...

**Comment by monkeystate** [comment]
Hello,

Are there any issues to resolve or can this be merged? It would be good to get the improved tests in master.

Thank you

**Review by riyazhakki — APPROVED** [review]
Changes looks good to me

**Comment by bayucan** [comment]
Merged #2242 into master.

**Pull request merged**
