### PR TITLE
server crash when a history job is deleted after a resource is deleted

### PR DESCRIPTION
**Pull request by saimanikant**
#### Describe Bug or Feature

The server crashes in the following way:
1. create resource foo
2.  turn on job history
3. add an epilogue hook which sets resources_used["foo"] = 10
4. wait until job has ended
5. delete resource foo
6. qdel -x history job

Backtrace:

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/pbs/sbin/pbs_server.bin'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004a9057 in free_resc (pattr=0x166e300) at attr_fn_resc.c:447
447				pr->rs_defin->rs_free(&pr->rs_value);
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 expat-2.1.0-12.el7.x86_64 glibc-2.17-317.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libical-3.0.3-2.el7.x86_64 libicu-50.2-4.el7_7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-3.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.44-22.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 postgresql-libs-9.2.24-4.el7_8.x86_64 python3-libs-3.6.8-18.el7.x86_64 sssd-client-1.16.5-10.el7_9.6.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00000000004a9057 in free_resc (pattr=0x166e300) at attr_fn_resc.c:447
#1  0x000000000043f73d in job_free (pj=0x166ddf0) at job_func.c:508
#2  0x000000000043fb41 in job_purge (pjob=pjob@entry=0x166ddf0) at job_func.c:1231
#3  0x0000000000459c75 in check_deletehistoryjob (preq=preq@entry=0x1670590, jid=jid@entry=0x7ffc4454dea0 "0.pbs-slave") at req_delete.c:294
#4  0x000000000045aa65 in req_deletejob (preq=preq@entry=0x1670590) at req_delete.c:478
#5  0x00000000004560bc in dispatch_request (sfds=sfds@entry=20, request=request@entry=0x1670590) at process_request.c:870
#6  0x0000000000456eaa in process_request (sfds=20) at process_request.c:700
#7  0x00000000004c0016 in process_socket (sock=sock@entry=20) at net_server.c:511
#8  0x00000000004c01e2 in wait_request (waittime=waittime@entry=2, priority_context=<optimized out>) at net_server.c:627
#9  0x000000000042a76a in main (argc=<optimized out>, argv=0x7ffc44550528) at pbsd_main.c:1418

#### Describe Your Change

 If you try and delete a resource and a job has it requested in Resource_List.foo, the delete request is rejected saying:
"resource busy on job"
Extending this to resources_used.

Test added for this in pbs_qdel.py , the deletion of history job happens in Teardown since server.delete() does not support '-x' option

#### Attach Test and Valgrind Logs/Output

[qdel_test_results_after.txt](https://github.com/openpbs/openpbs/files/5988299/qdel_test_results_after.txt)
[qdel_test_results_before.txt](https://github.com/openpbs/openpbs/files/5988300/qdel_test_results_before.txt)

In the before file, test errors in Teardown.

### CODE REVIEW

**Review by bhroam — CHANGES_REQUESTED** [review]

**Comment by bhroam** [comment]
Oh, @saimanikant, if you want to know how to history jobs, read through PTL's cleanup_jobs().  That's what is called from tearDown() which is deleting your jobs.  IIRC, you add extend='x' to delete(), but I might be wrong.  It's been a while since I looked at the function.

**Comment by saimanikant** [comment]
> 
> 
> Oh, @saimanikant, if you want to know how to history jobs, read through PTL's cleanup_jobs(). That's what is called from tearDown() which is deleting your jobs. IIRC, you add extend='x' to delete(), but I might be wrong. It's been a while since I looked at the function.

I had tried that. But it looks like delete() does not understand extend='x'

**Comment by saimanikant** [comment]
Latest test logs:
[qdel_test_results_after.txt](https://github.com/openpbs/openpbs/files/5994950/qdel_test_results_after.txt)

**Comment by bhroam** [comment]
I just looked at the cleanup_jobs() function.  It's extend='deletehist'

**Comment by saimanikant** [comment]
Updated Test logs:
[qdel_test_results_after.txt](https://github.com/openpbs/openpbs/files/6042427/qdel_test_results_after.txt)
[qdel_test_results_before.txt](https://github.com/openpbs/openpbs/files/6042429/qdel_test_results_before.txt)


> 
> 
> I just looked at the cleanup_jobs() function. It's extend='deletehist'

Thanks @bhroam . Please have a look at the latest changes

**Comment by bhroam** [comment]
I was actually fine with cleanup_jobs() doing the delete.  I was just trying to inform you of how it worked.  Sorry about the confusion.  This is fine too.  Will delete() throw an exception, or do we need to do a self.assertTrue(self.server.isUp())?

**Comment by saimanikant** [comment]
> 
> 
> I was actually fine with cleanup_jobs() doing the delete. I was just trying to inform you of how it worked. Sorry about the confusion. This is fine too. Will delete() throw an exception, or do we need to do a self.assertTrue(self.server.isUp())?

That's fine, I wanted the test to delete the job to complete the steps for reproducing the issue.
Since the test does a assertRaises() check while deleting the resource, this test won't proceed to crash (while deleting the job) server. So we don't need to check for server.isUp(). 
You will see the same in the latest logs in qdel_test_results_before.txt file.

**Review by bhroam — APPROVED** [review]
LGTM

**Review by bayucan — APPROVED** [review]
Looks fine.

**Comment by bayucan** [comment]
Merged #2257 into master.

**Pull request merged**
