### PR TITLE
updated std_dev, minimum and maximum of average_measurements in json report

### PR DESCRIPTION
**Pull request by birbalsain**
#### Describe Bug or Feature
For test run multiple times  minimum, maximum and  std_dev are average of the all run count.

#### Describe Your Change
In average measurement, for minimum and maximum taking minimum, maximum  among all the run count.
taking standard deviation of mean. 

#### Attach Test and Valgrind Logs/Output

[average_measurement.txt](https://github.com/openpbs/openpbs/files/6132812/average_measurement.txt)

### CODE REVIEW

**Review by visheshh — CHANGES_REQUESTED** [review]
You can use the same kind of list creation and use min() and max() for values.

**Comment by birbalsain** [comment]
> You can use the same kind of list creation and use min() and max() for values.

Already one for loop is in use if we use that same loop to compare  then it is good. If we use that loop only to store value in list and pass that list to min() then it is not good. In this case min() is not good.

**Comment by birbalsain** [comment]
[average_measurements.txt](https://github.com/openpbs/openpbs/files/6147510/average_measurements.txt)

**Review by visheshh — APPROVED** [review]
LGTM

**Review by prakashcv13 — APPROVED** [review]

**Pull request merged**
