### PR TITLE
Fix TestCgroupsHook to run on remote mom

### PR DESCRIPTION
**Pull request by shilpakodli**
#### Describe Bug or Feature
TestCgroupsHook tests were failing with different errors while checking for subsystem files on hosts. These subsystem files will be created on mom and test was checking locally.

#### Describe Your Change

- Changed find_main_path to have extra param as host
- Included hosts=self.hosts_list[0] in self.du.run_cmd, self.du.rm and self.du.cat commands
- Replaced all os.path.isfile, os.path.isdir with self.du.isfile and self.du.isdir respectively
- Also removed hostname from create_temp_file method call
- Splitted tearDown into two parts, one for cleaning up cgroups subsystems directories and second is to cleanup frozen jobs and also doing this on all hosts for safer side.
- Changed test_checkpoint_abort_preemption to run on a cluster which has more than two moms.
- changed job script self.sleep100_job to self.sleep600_job to avoid race conditions
- Changed walltime in cgroup_offline_node to have 600 seconds as walltime.
- Included '$clienthost': self.server.name in mom config file

#### No mom on server results:
Description: nomom_cgroups_latest
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7473|159|0|6|0|29|124|

6 tests failed on container due to sched config changes which is a known issue and is seen randomly on different test cases.
I reran failed tests and all of them have passed:

Description: Rerun Only Failed Tests From #7473
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7485|18|0|0|0|12|6|

#### Mom On server results:
Description: mom_on_server
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7466|159|0|0|0|27|132|

### CODE REVIEW

**Review by bayucan — CHANGES_REQUESTED** [review]
The changes you have looked good. THe only thing is that I did a search in the testsuite file and found other cases where run_cmd is being called but no hosts parameter. These could also be a problem. For instance:
test_big_cgroup_cpuset

 fn1 = self.get_cgroup_job_dir('cpuset', jid1, self.hosts_list[0])
        # Capture the output of cpuset_mem_script for job
4132        scr1 = self.du.run_cmd(cmd=[self.cpuset_mem_script % (fn1, None)],
                               as_script=True)

I've seen this in lines 
2861
4132
4381
4478
4566
4656
5315

**Comment by alexis-cousein** [comment]
What worries me is the extra two skips. That usually means that the test tried to set something up, failed, and _then_ decided to skip.

Could you give us the details of which tests were skipped when the server had no MoM, and why?

**Comment by shilpakodli** [comment]
Hi Alexis, results which I have attached are ran on Friday so logs are lost.
I have ran again with latest changes, however I see one test case "test_cgroup_prefix_and_devices" failed on Centos8 platform for which I haven't changed in my latest commit.

Description: nomom_on_server_cgroups
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7553|159|1|0|0|33|125|

Here is skip message info for 11 test cases:

test_big_cgroup_cpuset 
Reason = Test require >= 10 free vnodes

test_cgroup_enforce_memsw
Reason = no swap space available on the local host

test_cgroup_find_gpus 
Reason = Skipping test since nvidia-smi not found

test_cgroup_offline_node 
Reason = pbs_cgroups_hook: Failed to copy freezer state FROZEN

test_cgroup_offline_node_vnpernuma 
Reason = pbs_cgroups_hook: Failed to copy freezer state FROZEN

test_checkpoint_abort_preemption
Reason = test requires two MoMs as input, use -p moms=<mom1>:<mom2>

test_cpu_controller_enforce 
Reason = cpu group controller test: root cfs_quota_us is not unlimited, cannot test cgroup hook CPU quotas in this environment

test_cpu_controller_enforce_default 
Reason = cpu group controller test: root cfs_quota_us is not unlimited, cannot test cgroup hook CPU quotas in this environment

test_cpu_controller_enforce_default_zero_job 
Reason = cpu group controller test: root cfs_quota_us is not unlimited, cannot test cgroup hook CPU quotas in this environment

test_cpu_controller_enforce_zero_job 
Reason = cpu group controller test: root cfs_quota_us is not unlimited, cannot test cgroup hook CPU quotas in this environment

test_vnodepernuma_use_hyperthreads 
Reason = too many jobs (80) to submit

**Comment by alexis-cousein** [comment]
These two are probably not normal:

test_cgroup_offline_node
Reason = pbs_cgroups_hook: Failed to copy freezer state FROZEN

test_cgroup_offline_node_vnpernuma
Reason = pbs_cgroups_hook: Failed to copy freezer state FROZEN

I'll give the logs a read on Monday. I'm changing these in another PR to make them run on a test harness that has restrictive sudo rules, so I'm familiar with them.

**Comment by shilpakodli** [comment]
Thanks Alexis and Al for the review, apart from test_cgroup_offline_node and test_cgroup_offline_node_vnpernuma, I do not see any other issue. I reran all the tests on TH with extensions repo given, and all tests passed on all platforms.
I request you @alexis-cousein and @bayucan to review my latest code changes.

Description: Rerun All Tests From #7553
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7565|477|0|0|0|99|378|

**Comment by alexis-cousein** [comment]
As I said, there's something wrong with copying the file over to freeze the freezer cgroup made for the tow extra skipped tests:

2021-05-13 11:12:48,172 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u pbsuser7 ls /home/pbsuser7
2021-05-13 11:12:48,881 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 /usr/bin/rm /tmp/PtlPbsx652llwo
2021-05-13 11:12:51,368 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u pbsother ls /home/pbsother
2021-05-13 11:12:52,798 INFOCLI2 x7565-65-0(run_cmd): /usr/bin/scp /tmp/PtlPbs9_m7y09_ x7565-65-1.x7565-65.th.svc.cluster.local:/tmp/PtlPbs9_m7y09_
2021-05-13 11:12:55,297 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u pbstest ls /home/pbstest
2021-05-13 11:13:00,370 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u tstusr00 ls /home/tstusr00
2021-05-13 11:13:01,885 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 ls -1 /opt/pbs/python/bin/python
2021-05-13 11:13:05,893 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u tstusr01 ls /home/tstusr01
2021-05-13 11:13:07,688 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 /opt/pbs/python/bin/python -c "import tempfile;print(tempfile.mkstemp('PtlPbstmpcopy')[1])"
2021-05-13 11:13:09,474 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u pbsoper ls /home/pbsoper
2021-05-13 11:13:12,281 INFOCLI2 x7565-65-0(run_cmd): /usr/bin/scp -p /tmp/PtlPbs9_m7y09_ x7565-65-1.x7565-65.th.svc.cluster.local:/tmp/tmpcnrbhcaxPtlPbstmpcopy
2021-05-13 11:13:13,392 INFOCLI2 x7565-65-1(run_cmd): ssh x7565-65-1 sudo -H -u pbsmgr ls /home/pbsmgr
2021-05-13 11:13:15,980 ERROR    <DshUtils.run_cmd>cmd:/usr/bin/scp -p /tmp/PtlPbs9_m7y09_ x7565-65-1.x7565-65.th.svc.cluster.local:/tmp/tmpcnrbhcaxPtlPbstmp copy err: ['/tmp/PtlPbs9_m7y09_: No such file or directory']

**Comment by alexis-cousein** [comment]
Also, please **review** Al''s comments. It's not because you can't see a failed test that the code does not need fixing.

E.g. at the end of the 'offline' tests, we clean up the freezer cgroup that was created, and on line 2861 we have (quoting from the comment for the section):

```
        # once the freezer is thawed, all the processes should receive
        # the cgroup hook's kill signal and disappear;
        # confirm they're gone before deleting freezer
        freezer_tasks = os.path.join(fdir_pbs, 'tasks')
        for count in range(30):
            ret = self.du.cat(hostname=self.hosts_list[0],
                              filename=freezer_tasks,
                              sudo=True)
            if ret['rc'] != 0:
                self.logger.info("Cannot confirm freezer tasks"
                                 "sleeping 30 seconds instead")
                time.sleep(30)
                break
            if ret['out'] == [] or ret['out'][0] == '':
                self.logger.info("Processes in thawed freezer are gone")
                break
            else:
                self.logger.info("tasks still in thawed freezer: "
                                 + str(ret['out']))
                time.sleep(1)

        cmd = ["rmdir", fdir_pbs]
        self.logger.info("Removing %s" % fdir_pbs)
        self.du.run_cmd(cmd=cmd, sudo=True)
```
If you read the comment it's obvious we want to clean up the freezer directory on the MoM host, so that "cmd" definitely wants to run on self.hosts_list[0].

**Comment by alexis-cousein** [comment]
I would also make the intent of the following snippet more explicit:
```
                r1 = self.du.run_cmd(cmd=['cat', svr_conf], sudo=True)
                r2 = self.du.run_cmd(cmd=['cat', mom_conf], sudo=True,
                                     hosts=self.mom.shortname)
```

by adding hosts=self.serverA to the first run_cmd. That way it's _explicit_ that the first line refers to looking up the file on the server.

**Comment by alexis-cousein** [comment]
The cleanup is also not 'clean':

```
                        for tasks_file in tasks_files:
                            jdir = os.path.dirname(tasks_file)
                            if not os.path.isdir(jdir):

```

is looking up whether a path for a cgroup exists locally (instead of on the first MoM host)

and 
```
                            cmd2 = ['rmdir', jdir]
                            self.du.run_cmd(cmd=cmd2, sudo=True)
```
is cleaning up the directory on the PTL host as well (incidentally, that's another line that Al asked you to review because of a 'naked' run_cmd).

In fact, for a good cleanup, we should do the cleanup on ALL the hosts, i.e. have a loop across the hosts in self.hosts_list , not just clean up on self.hosts_list[0].

**Comment by alexis-cousein** [comment]
Another error:

```
        if not self.du.isdir(fdir_pbs):
            self.du.mkdir(hostname=self.hosts_list[0], path=fdir_pbs,
                          mode=0o755, sudo=True)
```
Evidently, the directory should be created unless it exists on self.hosts_list[0], so the self.du.isdir is also failing to specify the host.

**Comment by alexis-cousein** [comment]
Another error:

```
                if os.path.isdir(cdir):
```

That should be using self.du.isdir and specifying the correct host as well.

**Comment by shilpakodli** [comment]
Hi @alexis-cousein I have addressed your comments except freezer.state part where we need to echo directly without creating a temp file. I am still having sudo issues in writing something to cgroups directory. Once it is fixed I will push those changes. Kindly review the latest changes. Will attach the results in sometime.

**Comment by shilpakodli** [comment]
Hi @alexis-cousein please find the latest results:
Description: nomom_cgroups
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7642|477|0|0|0|81|396|

**Comment by shilpakodli** [comment]
Hi @alexis-cousein and @bayucan Please review my PR. I am done with all the changes. Few tests still failing randomly due to race conditions. But I will be fixing these race conditions in another PR as this is going out of scope for this PR. Please give your feedback on code changes.
Description: nomom_cgroups
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7698|477|1|0|0|72|404|

**Review by bayucan — APPROVED** [review]
Looks good.

**Comment by shilpakodli** [comment]
Thanks Al for the sign off.

**Comment by alexis-cousein** [comment]
Loks good.

**Comment by bayucan** [comment]
Merged #2385 into master.

**Pull request merged**
