### PR TITLE
Performace: Removing job attribute 'pset'

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Describe Bug or Feature

Around a year back, there was a discussion around the job's pset attribute, it was deprecated in 2020, so we can remove it now (refer to https://community.openpbs.org/t/deprecate-pset-job-attribute/2031). That's exactly what this PR does. Since we use placement sets to do server local scheduling in multi-server mode, there's a pset related alterjob request sent to the server for every job that's run, so removing the attribute should help with performance in multi-server mode.

#### Attach Test and Valgrind Logs/Output

Notice the Type 96 (async alterjob) request message in the server logs below
**Before**:
```
03/10/2021 17:03:56;0100;Server@pbsproc8;Req;;Type 51 request received from Scheduler@pbsproc8, sock=16
03/10/2021 17:03:56;0100;Server@pbsproc8;Req;;Type 96 request received from Scheduler@pbsproc8, sock=16
03/10/2021 17:03:56;0100;Server@pbsproc8;Hook;;modifyjob event: accept req by default
03/10/2021 17:03:56;0008;Server@pbsproc8;Job;400.pbsproc8;Job Modified at request of Scheduler@pbsproc8
03/10/2021 17:03:56;0100;Server@pbsproc8;Req;;Type 23 request received from Scheduler@pbsproc8, sock=16
03/10/2021 17:03:56;0100;Server@pbsproc8;Node;pbsproc8;set_vnode_state;vnode.state=0x0 vnode_o.state=0x0 vnode.last_state_change_time=1615395836 vnode_o.last_state_change_time=1615395823 state_bits=0xffffffffffffffaf state_bit_op_type_str=Nd_State_And state_bit_op_type_enum=2
03/10/2021 17:03:56;0008;Server@pbsproc8;Job;400.pbsproc8;Job Run at request of Scheduler@pbsproc8 on exec_vnode (pbsproc8:ncpus=1)
```

**After**:
```
03/10/2021 17:14:20;0100;Server@pbsproc8;Req;;Type 51 request received from Scheduler@pbsproc8, sock=16
03/10/2021 17:14:20;0100;Server@pbsproc8;Req;;Type 23 request received from Scheduler@pbsproc8, sock=16
03/10/2021 17:14:20;0100;Server@pbsproc8;Node;pbsproc8;set_vnode_state;vnode.state=0x0 vnode_o.state=0x0 vnode.last_state_change_time=1615396460 vnode_o.last_state_change_time=1615396349 state_bits=0xffffffffffffffaf state_bit_op_type_str=Nd_State_And state_bit_op_type_enum=2
03/10/2021 17:14:20;0008;Server@pbsproc8;Job;500.pbsproc8;Job Run at request of Scheduler@pbsproc8 on exec_vnode (pbsproc8:ncpus=1)
```

### CODE REVIEW

**Comment by bhroam** [comment]
I thought we deprecated pset in 2021, so we can remove it in 2022.

**Comment by agrawalravi90** [comment]
it was actually deprecated in 2020 .. does this mean we can remove it now?

**Comment by bhroam** [comment]
The general rule of thumb is if it is deprecated in one release, we can get rid of it in the next.  Usually we need yet another design saying that though.  Maybe you can just update the original with an 'update' section saying it is being obsoleted.

**Comment by agrawalravi90** [comment]
@bhroam thanks, I've updated the EDD to add removal of the attribute, added a comment on the forum for the same, and changed the PR to remove it, check it out.

**Review by bhroam — APPROVED** [review]
Looks good.  Do any PTL tests use it?

**Comment by agrawalravi90** [comment]
regression results:
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6422|3990|36|6|0|0|3948|

Description: Rerun Only Failed Tests From #6422
Platforms: CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6426|42|29|8|0|0|5|

Description: Rerun Only Failed Tests From #6426
Platforms: CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6459|37|0|0|0|0|37|

**Comment by agrawalravi90** [comment]
@bhroam i dont think so, but i had some failures in regression which went away after my latest commit, please review it once

**Review by bhroam — APPROVED** [review]

**Review by subhasisb — APPROVED** [review]

**Pull request merged**
