### PR TITLE
pbs_mom fails to come up, calling log_open again fails

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Describe Bug or Feature

with https://github.com/openpbs/openpbs/pull/2227 we replaced a perror call with log_err, but it occurred before the call to log_open, so it opens the log with /dev/console. Since we don't exit the process in this particular instance, we go on and inside mom_main.c, we call log_open a second time, which make pbs_mom exit with failure

#### Describe Your Change

Changed log_open to just close existing log when called a second time and proceed instead of exiting with error

#### Attach Test and Valgrind Logs/Output

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5955|3815|1|0|0|13|3801|

Description: Rerun Only Failed Tests From #5955
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5957|1|0|0|0|0|1|

### CODE REVIEW

**Review by ashwathraop — APPROVED** [review]

**Review by hirenvadalia — APPROVED** [review]

**Comment by hirenvadalia** [comment]
@agrawalravi90 Please attach test results...

**Review by subhasisb — CHANGES_REQUESTED** [review]
log_err() seems to handle being called before log_open(), see these lines:

if (log_opened == 0)
      (void)log_open("/dev/console", log_directory);

Please check

**Comment by agrawalravi90** [comment]
@subhasisb  Thanks for catching that, I've changed log_open to just close existing log and open new log file, like you suggested. Please let me know if it looks ok now.

**Comment by agrawalravi90** [comment]
> @agrawalravi90 Please attach test results...

unfortunately, there's none. I test this by adding a dummy log_err at the top of mom's main. it used to fail before with the error message mentioned in the description, and now it passes. Code inspection should be good enough for this, it's a pretty safe code change. But I'll do a regression.

**Review by ashwathraop — APPROVED** [review]
Thanks for changing it. This looks better.

**Review by subhasisb — APPROVED** [review]

**Pull request merged**
