### PR TITLE
Fixes to printjob

### PR DESCRIPTION
**Pull request by agrawalravi90**
#### Describe Bug or Feature

Couple of fixes:
- Reverting the state field value back to being a numeric instead of a letter
- Fixing substate field value, it was printing the decimal value instead of hex

#### Attach Test and Valgrind Logs/Output

**Before:**
state:                    R
substate:             0x42 (42)

**After:**
state:		0x4
substate:	0x2a (42)

**PTL test logs:**
[test.log](https://github.com/openpbs/openpbs/files/5502732/test.log)

### CODE REVIEW

**Review by vstumpf — APPROVED** [review]
LGTM

**Review by subhasisb — APPROVED** [review]

**Comment by subhasisb** [comment]
Can you attach any kind of test logs please

**Comment by agrawalravi90** [comment]
@subhasisb added ptl test and logs, thanks

**Comment by agrawalravi90** [comment]
@vstumpf can you please take a look at the PTL test once and let me know if it looks ok? thanks

**Review by vstumpf — APPROVED** [review]
LGTM

**Pull request merged**
