### PR TITLE
Allow to override the default scp flags

### PR DESCRIPTION
**Pull request by fnevgeny**
I had to change the scp flags (specifically, add "-4" to stick to IPv4 in dual-stack nodes) and, to my surprise, found the default flags are hardcoded. So, this patch adds the functionality. The possibility to disable the excessively verbose "scp -v" output - when not debugging - is also a boon, IMO :).

### CODE REVIEW

**Review by bhroam — APPROVED** [review]

**Comment by bayucan** [comment]
@fnevgeny Looks good. Do you have any evidence of testing?

**Comment by fnevgeny** [comment]
> @fnevgeny Looks good. Do you have any evidence of testing?

Yes, I've tested it on a few nodes. I haven't done a full rollout yet.

**Comment by bayucan** [comment]
> > @fnevgeny Looks good. Do you have any evidence of testing?
> 
> Yes, I've tested it on a few nodes. I haven't done a full rollout yet.

Once you attach the test results, I'll merge your pull request.

**Comment by fnevgeny** [comment]
Hmm, what kind of test results? It seems when scp succeeds, there is no trace of it in the logs; am I missing something?

I can artificially prohibit a node from accessing the submission host; then:

```
# grep SCP_ARGS /etc/pbs.conf
PBS_SCP_ARGS=-4Brp
# grep scp /var/spool/pbs/mom_logs/20240817 
08/17/2024 00:54:41;0080;pbs_mom;Fil;sys_copy;command: /bin/scp -4Brp /var/spool/pbs/spool/124350.pbs.OU fnevgeny@*****:/tmp/test.o124350 status=255, try=1
08/17/2024 00:55:23;0080;pbs_mom;Fil;sys_copy;command: /bin/scp -4Brp /var/spool/pbs/spool/124350.pbs.OU fnevgeny@*****:/tmp/test.o124350 status=255, try=3
```
Otherwise, the jobs run fine, and the data are transferred correctly.

**Review by bayucan — APPROVED** [review]

**Pull request merged**
