### PR TITLE
qdel only prints error message for the first job

### PR DESCRIPTION
**Pull request by nithinj**
#### Describe Bug or Feature
Qdel only prints an error message for the first error it encounters.

#### Describe Your Change
Fixed an issue while linking two lists. Assigning last->next = new instead of head->next = new

#### Attach Test and Valgrind Logs/Output
Before:
[root@centos8_2 target]# qdel 3100 3101
qdel: Unknown Job Id 3100

After:
[root@centos8 target]# qdel 3000 3001
qdel: Unknown Job Id 3000
qdel: Unknown Job Id 3001

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7401|4164|6|30|0|1|4127|

Description: Rerun Only Failed Tests From #7401
Platforms: SUSE15,RHEL8,SLES12
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7406|36|0|0|0|0|36|

### CODE REVIEW

**Comment by nithinj** [comment]
Requesting reviews from @agrawalravi90 , @bremanandjk

**Review by agrawalravi90 — COMMENTED** [review]
LGTM, please attach regression logs

**Review by bremanandjk — APPROVED** [review]
LGTM

**Comment by nithinj** [comment]
@agrawalravi90 , I have updated the test results. Please have a look!

**Review by agrawalravi90 — APPROVED** [review]

**Pull request merged**
