### PR TITLE
Change job submission user to pbsroot

### PR DESCRIPTION
**Pull request by RKORavi**
#### Describe Bug or Feature
To run cat command on job's output file user should have sudo privileges

#### Describe Your Change
Changing job submission user to pbsroot

### CODE REVIEW

**Comment by RKORavi** [comment]
Test logs:
[1592-ALL.zip](https://github.com/PBSPro/pbspro/files/4621705/1592-ALL.zip)

**Comment by bhroam** [comment]
@RKORavi I don't understand why the change to PBSROOT_USER over TEST_USER.  Your PR description says you need sudo privileges, but pbsroot is just another user.  It isn't root.  The benefit of using TEST_USER is it is the default user for jobs.

**Comment by RKORavi** [comment]
> @RKORavi I don't understand why the change to PBSROOT_USER over TEST_USER. Your PR description says you need sudo privileges, but pbsroot is just another user. It isn't root. The benefit of using TEST_USER is it is the default user for jobs.

Hi @bhroam,
To run cat command on job's output file sudo privileges is required. On some setup TEST_USER do not have sudo privileges this results in failure of test cases.

**Comment by bhroam** [comment]
@RKORavi I still don't understand.  When you do a self.du.cat(), it is run by the person who is running the test.  In our testbed case, that will be pbsroot.  If you need cat() to run as a different user, user the runas argument.

**Comment by RKORavi** [comment]
> @RKORavi I still don't understand. When you do a self.du.cat(), it is run by the person who is running the test. In our testbed case, that will be pbsroot. If you need cat() to run as a different user, user the runas argument.

@bhroam did not think of that. Thankyou I will make the changes.

**Comment by RKORavi** [comment]
> > @RKORavi I still don't understand. When you do a self.du.cat(), it is run by the person who is running the test. In our testbed case, that will be pbsroot. If you need cat() to run as a different user, user the runas argument.
> 
> @bhroam did not think of that. Thankyou I will make the changes.

@bhroam our testbed machines seems come permission issue. So, this PR might not be required. I will update on this PR after confirming.

**Comment by hirenvadalia** [comment]
Closing long time inactive PR.

**Pull request closed without merging**
