### PR TITLE
Remove failover code

### PR DESCRIPTION
**Pull request by ashwathraop**
#### Describe Bug or Feature

There are better tools outside PBS that can manage high availability than PBS's software failover feature. Admins can have better control of high availability by using tools like pacemaker and corosync.

#### Describe Your Change

Remove failover feature related code from PBS core.

#### Link to Design Doc

https://openpbs.atlassian.net/wiki/spaces/PD/pages/2114945027/High+availability+using+pacemaker+and+corosync.

#### Attach Test and Valgrind Logs/Output

<Tests running>

### CODE REVIEW

**Review by hirenvadalia — CHANGES_REQUESTED** [review]
@ashwathraop With this changes I still see few code/comments (mostly comments) related to failover, please search failover word in whole code base and remove which are not needed.

**Review by hirenvadalia — APPROVED** [review]
@ashwathraop Please post full regression results and also please do build on other platforms also

**Comment by subhasisb** [comment]
@ashwathraop  we are making changes to external interfaces like PBS_PRIMARY, PBS_SECONDARY, switches in qstat, so we must document those in some external design doc

**Review by subhasisb — CHANGES_REQUESTED** [review]
Code changes look fine, however need the approval to remove the PBS_PRIMARY, PBS_SECONDARY switches as well the qstat switches related to failover

**Comment by ashwathraop** [comment]
Test results
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4514|3848|7|1|0|5|3835|

Failures are on master and not related to this PR.

**Pull request closed without merging**
