### PR TITLE
Replacing MSG_OOB for MSG_PEEK in qsub

### PR DESCRIPTION
**Pull request by nithinj**
#### Describe Bug or Feature
* Replacing MSG_OOB for MSG_PEEK from qsub
* Why the code exists is puzzling when the server does not send any MSG_OOB

#### Describe Your Change
* MSG_OOB exists today to find out whether the server had closed the connection. Replacing it with MSG_PEEK and adding a comment to explain why it is there.

#### Attach Test and Valgrind Logs/Output
```
[root@head1 pbspro]# qsub -- /bin/sleep 100
25032.head1
```

Regression
--------------
Description: Tests from given sources on platforms UBUNTU1804, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, UBUNTU2004
Platforms: UBUNTU1804,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|8340|4117|3|0|0|0|4114|

### CODE REVIEW

**Review by subhasisb — APPROVED** [review]

**Review by ashwathraop — APPROVED** [review]
Please look at failed CI builds.

**Comment by nithinj** [comment]
@subhasisb & @ashwathraop ,
Thanks for the review. MSG_OOB was present to detect whether the server had closed the connection from qsub daemon and exit the daemon in such a case. I had replaced MSG_OOB with MSG_PEEK and added a comment to explain what the code does. Please have a peek.

**Comment by agrawalravi90** [comment]
@nithinj please post regression results

**Review by ashwathraop — APPROVED** [review]

**Review by subhasisb — APPROVED** [review]

**Comment by subhasisb** [comment]
> @subhasisb & @ashwathraop ,
> Thanks for the review. MSG_OOB was present to detect whether the server had closed the connection from qsub daemon and exit the daemon in such a case. I had replaced MSG_OOB with MSG_PEEK and added a comment to explain what the code does. Please have a peek.

Yeah sorry forgot. It was probably me who added that code long long back...! And peek makes much more sense than oob! Thanks!

**Pull request merged**
