### PR TITLE
Fixing test test_res_string

### PR DESCRIPTION
**Pull request by tpai26**
#### Describe Bug or Feature
The job sleep time is set to 5 seconds. This sometimes fails on slower machines because the job ends before the expect can check if the job is in R state. Removing the custom added sleep time for the job and keeping it to default sleep time.

#### Attach Test and Valgrind Logs/Output
[test_res_string.txt](https://github.com/openpbs/openpbs/files/5177188/test_res_string.txt)
[test_res_string_array.txt](https://github.com/openpbs/openpbs/files/5177189/test_res_string_array.txt)
[test_res_size.txt](https://github.com/openpbs/openpbs/files/5177190/test_res_size.txt)
[test_multiple_res.txt](https://github.com/openpbs/openpbs/files/5177191/test_multiple_res.txt)

### CODE REVIEW

**Review by bhroam — APPROVED** [review]
LGTM

**Review by vstumpf — CHANGES_REQUESTED** [review]
I think you need to delete the job; on a machine with one cpu, the limiting resource will probably be ncpus

**Comment by vstumpf** [comment]
It looks like the 5 second jobs were added in #1572, maybe you should check the other tests to see if the same need to be done?

**Review by bhroam — APPROVED** [review]

**Review by vstumpf — APPROVED** [review]
LGTM

**Review by bhroam — APPROVED** [review]

**Pull request merged**
