### PR TITLE
Add support for python 3.10

### PR DESCRIPTION
**Pull request by nsouedet**
Fixes errors that occur in cgroups hook on Ubuntu 22.04 with python 3.10.
As this pull request is to fix issues on Ubuntu 22.04 it should be linked to #2562.

#### Bug
Using the cgroups hook on Ubuntu 22.04 fails with the error `SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats`

#### Changes
Implementation of the mandatory changes for python 3.10 in C-api arguments parsing (see https://docs.python.org/3/c-api/arg.html and https://docs.python.org/3.10/extending/extending.htm).
The definition of PY_SSIZE_T_CLEAN macro is mandatory since python 3.10. It is thus necessary to add `#define PY_SSIZE_T_CLEAN`  before each `#include <Python.h>`. This lead to use Py_ssize_t type to get argument length in PyArg_Parse* calls.

### CODE REVIEW

**Review by nithinj — CHANGES_REQUESTED** [review]
It will be cleaner to include pbs_python_private.h wherever appropriate, within Libpython and python modules so that we dont have to redefine the macro.

**Comment by nithinj** [comment]
please attach a build log from Ubuntu22 as the CI does not check for that.

**Comment by hirenvadalia** [comment]
> please attach a build log from Ubuntu22 as the CI does not check for that.

@nsouedet I would suggest to add ubuntu 22 in CI, so this change can get tested as part of CI.

**Comment by nsouedet** [comment]
> > please attach a build log from Ubuntu22 as the CI does not check for that.
> 
> @nsouedet I would suggest to add ubuntu 22 in CI, so this change can get tested as part of CI.

For sure, it is a far better idea. But as I am a complete newbe in openpbs contribution, I neither know how to setup CI environment for tests nor how to add a new OS. Is there some documentation or guidelines for this ?
Many thanks

**Comment by nithinj** [comment]
@nsouedet & @hirenvadalia 

I believe adding CI can be an independent PR. For now, the build logs would be sufficient.
As far as adding U22 into CI, we need to add a new Azure pipeline for it, as well as any necessary changes in the ci/ directory. There is a Readme file within ci/ dir.

**Comment by nithinj** [comment]
@hirenvadalia 
I do not have permission to edit the azure pipeline.

**Comment by nsouedet** [comment]
Hello, the pull request has been updated to integrate your suggestions. The macro has been replaced by including pbs_python_private.h. Once it is merged, I'll do a pull request to integrate changes for Ubuntu 22.04 in CI.

**Review by nithinj — APPROVED** [review]

**Comment by nithinj** [comment]
@hirenvadalia please review the latest changes

**Review by hirenvadalia — APPROVED** [review]

**Pull request merged**
