### PR TITLE
add PTL TestMomHookSync.test_rescdef_mom_recreate to test #efa7bfa

### PR DESCRIPTION
**Pull request by Shrini-h**
#### Describe Bug or Feature

The fix in https://github.com/openpbs/openpbs/commit/efa7bfac8fa41815f3c5e7681b5fa1fc57a754b8 can be tested using automation

#### Describe Your Change

Added automated PTL test case `TestMomHookSync.test_rescdef_mom_recreate` for testing the fix https://github.com/openpbs/openpbs/commit/efa7bfac8fa41815f3c5e7681b5fa1fc57a754b8

#### Attach Test and Valgrind Logs/Output

[ptl_out_bug.txt](https://github.com/openpbs/openpbs/files/5280922/ptl_out_bug.txt)
[ptl_out_fixed.txt](https://github.com/openpbs/openpbs/files/5280923/ptl_out_fixed.txt)

### CODE REVIEW

**Comment by Shrini-h** [comment]
To Automate testing of https://github.com/openpbs/openpbs/pull/2041

**Review by bayucan — APPROVED** [review]
Looks good.

**Review by npadole20 — APPROVED** [review]

**Review by SudeshnaMoulik — APPROVED** [review]
LGTM

**Comment by bayucan** [comment]
Merge #2044 into master.

**Pull request merged**
