### PR TITLE
fixed test 'test_auto_sched_cycle_trigger' from 'TestVerifyLogOutput' failed in assertion error.

### PR DESCRIPTION
**Pull request by dinesh1306**
#### Describe Bug or Feature

fixed test 'test_auto_sched_cycle_trigger' from 'TestVerifyLogOutput' failed in assertion error.
test failed in assertion. In test PTL expect 'Req;;Starting Scheduling Cycle' log message in 10 attempts, logs are appeared in sched_logs, but sometime race condition occurred such that PTL didn't get expected log_match in 10 attempts and test got failed in assertion.  

#### Describe Your Change

remove max_attempts=10 from the log_match.

#### Attach Test and Valgrind Logs/Output

Before Fix:
[before_fix.txt](https://github.com/openpbs/openpbs/files/6694050/before_fix.txt)
After Fix:
[res_test_auto_sched_cycle_trigger_1.txt](https://github.com/openpbs/openpbs/files/6694054/res_test_auto_sched_cycle_trigger_1.txt)
[res_test_auto_sched_cycle_trigger_2.txt](https://github.com/openpbs/openpbs/files/6694055/res_test_auto_sched_cycle_trigger_2.txt)
[res_test_auto_sched_cycle_trigger_3.txt](https://github.com/openpbs/openpbs/files/6694056/res_test_auto_sched_cycle_trigger_3.txt)
[res_test_auto_sched_cycle_trigger_4.txt](https://github.com/openpbs/openpbs/files/6694058/res_test_auto_sched_cycle_trigger_4.txt)
[res_test_auto_sched_cycle_trigger_5.txt](https://github.com/openpbs/openpbs/files/6694059/res_test_auto_sched_cycle_trigger_5.txt)

### CODE REVIEW

**Review by shilpakodli — APPROVED** [review]

**Review by bhroam — APPROVED** [review]
This looks fine.  If you want to take this one step further, I'd remove the try/except.  Just let the log_match() raise its exception.  It isn't like the assert is printing a message or anything.

**Comment by bhroam** [comment]
@dinesh1306 Let me know if you want to do my suggestion.  If not, I'll merge the PR (or you can have Prakash do it).

**Comment by dinesh1306** [comment]
@bhroam , I will change code and push new commit.

**Comment by dinesh1306** [comment]
Hi @bhroam , I have change the code. Please take a look.
[res__after_change_4.txt](https://github.com/openpbs/openpbs/files/6699661/res__after_change_4.txt)
[res__after_change_5.txt](https://github.com/openpbs/openpbs/files/6699663/res__after_change_5.txt)
[res__after_change_1.txt](https://github.com/openpbs/openpbs/files/6699664/res__after_change_1.txt)
[res__after_change_2.txt](https://github.com/openpbs/openpbs/files/6699665/res__after_change_2.txt)
[res__after_change_3.txt](https://github.com/openpbs/openpbs/files/6699666/res__after_change_3.txt)

**Review by bhroam — APPROVED** [review]

**Pull request merged**
