### PR TITLE
use cJSON for json output generation

### PR DESCRIPTION
**Pull request by vchlum**
#### Describe Bug or Feature

As discussed in #2603 , this PR replaces custom JSON implementation to [cJSON](https://github.com/DaveGamble/cJSON) ~~version 1.7.16~~.

#### Describe Your Change

~~The function name add_json_node() is reused and its semantics are preserved. The inside of the function is brand new. It means the function is still called to start (or end) an object (or an array) and also to put a value inside the current object (or an array). So cJSON functions are not exposed outside add_json_node().~~

~~cJSON does not have reference to the parent node, so the node path to the currently constructed node is kept by static functions json_path_down() and json_path_up() inside add_json_node(). Once the construction of a deeper object or array is finished, calling json_path_up() sets the parent node as the current node.~~

The cJSON uses different ASCII escaping than the custom json formatting. It uses rather escaped `\u001b[1m` than `^[[1m`, which means the ptl test testing non-printable chars had to be changed. In the ptl test, the resulting text is evaluated and escaped again in the form used in the test. So it is shown the formatting of non-printable chars is preserved.

~~The cJSON is imported [as is](https://github.com/DaveGamble/cJSON/releases/tag/v1.7.16), with no changes. Once a new version is needed, we can simply replace cJSON.h and cJSON.c.~~

The files pbs_json.* were removed and the code was replaced by cJSON functions.  CI was changed in order to compile with cJSON.

#### Attach Test and Valgrind Logs/Output

pbsnodes example: [cJSON_pbsnodes.txt](https://github.com/openpbs/openpbs/files/12136512/cJSON_pbsnodes.txt)
qstat example: [cJSON_qstat.txt](https://github.com/openpbs/openpbs/files/12136513/cJSON_qstat.txt)

ptl test pbs_nodes_json: [ptl_output-pbs_nodes_json.txt](https://github.com/openpbs/openpbs/files/12136519/ptl_output-pbs_nodes_json.txt)
ptl test pbs_qstat_formats: [ptl_output-pbs_qstat_formats.txt](https://github.com/openpbs/openpbs/files/12136520/ptl_output-pbs_qstat_formats.txt)
selected ptl tests of pbs_nonprint_characters: [ptl_output-pbs_nonprint_characters-selected.txt](https://github.com/openpbs/openpbs/files/12136521/ptl_output-pbs_nonprint_characters-selected.txt) (few tests in the file pbs_nonprint_characters fail, the test are unrelated to this change (fail anyway) so only selected and related test are used)

### CODE REVIEW

**Comment by nithinj** [comment]
@vchlum 
We may not want to embed the code within PBS. Can we make use of the cjson library from the system?
This would be better for maintenance.

**Comment by nithinj** [comment]
@vchlum 
We may also want to remove any existing cjson library code that is no longer required.
This is a big undertaking! Thanks.

**Comment by vchlum** [comment]
Oh sorry. I had not used the cjSON before I read the documentation because of this PR and it is written you can easily source the cJSON to a project. I did not realize it is so widely spread across system packages:-). Surely, I will change to cJSON system library.

@nithinj Could you please explain 'remove any existing cjson library code that is no longer required'? If I move from the embedded solution to the system library, there will be no extra code... ?? I searched the PBS code for the string 'json' and I did not see any unused json code. Did I search poorly?:-) I will happily do the work. I am just not sure what you mean.

**Comment by nithinj** [comment]
@vchlum 
We should remove the existing pbs_json.* files if we can.

**Comment by vchlum** [comment]
[bbba0d0](https://github.com/openpbs/openpbs/pull/2604/commits/bbba0d04df48eefbcf6d11593cacf063a4502195) not popped up here. So, I amended and force-pushed

@nithinj I removed pbs_json.* and cJSON is not embedded any more. The cjson library is not in the repository of supported systems like centos 7 and ubuntu 18. I am not sure if this is an issue. Couldn't we remove such systems from supported and moved the ci to centos 8? I can create another PR for this later. For now, I have resolved it by compiling cJSON in ci. The old systems do not get full updates anymore.

New ptl tests:
[ptl_output-pbs_nodes_json.txt](https://github.com/openpbs/openpbs/files/12184417/ptl_output-pbs_nodes_json.txt)
[ptl_output-pbs_nonprint_characters-selected.txt](https://github.com/openpbs/openpbs/files/12184414/ptl_output-pbs_nonprint_characters-selected.txt)
[ptl_output-pbs_qstat_formats.txt](https://github.com/openpbs/openpbs/files/12184419/ptl_output-pbs_qstat_formats.txt)

**Review by nithinj — APPROVED** [review]

**Review by nithinj — CHANGES_REQUESTED** [review]
@vchlum 
The only issue with this is that the cjson function is not adhering to pbs standards. PBS does not use camel case (cJSON_CreateObject). PBS function would have been json_create() / json_createobject().

Usually we wrap the third party functions before using within PBS. You can take a look at how we deal with postgres.
I think we are better off having a pbs_json.* that has all the cjson function calls and PBS just uses what we defined in them. That way we can customize the functions. It will also help us to switch into a different third party json library if needed.

**Comment by vchlum** [comment]
@nithinj I wrapped cJSON. It is now isolated in libjson.

New ptl tests:
[ptl_output-pbs_nodes_json.txt](https://github.com/openpbs/openpbs/files/12236611/ptl_output-pbs_nodes_json.txt)
[ptl_output-pbs_nonprint_characters-selected.txt](https://github.com/openpbs/openpbs/files/12236612/ptl_output-pbs_nonprint_characters-selected.txt)
[ptl_output-pbs_qstat_formats.txt](https://github.com/openpbs/openpbs/files/12236613/ptl_output-pbs_qstat_formats.txt)

**Review by nithinj — APPROVED** [review]
Changes looks good to me!

**Review by bayucan — APPROVED** [review]
Looks fine.

**Pull request merged**
